import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Navbar/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"
      />
      <body className={inter.className}>
        <div className=" p-4 bg-white shadow-lg fixed w-full z-[99999] ">
          <Navbar />
        </div>


        {children}
        <section className='bg-black rounded-t-[4rem]  padding-x padding-t pb-8'>
          <Footer />
        </section>

      </body>
    </html>
  );
}
